In [1]:
import math
import numpy as np

In [2]:
# XOR
data = np.array([
    [0, 0, 1, 1],
    [0, 1, 0, 1],
    [0, 1, 1, 0]])
X = data[:-1, :]
Y = data[-1, :]

In [3]:
def sigmoid(x: np.ndarray):
    return 1/(1+np.exp(-x))

def loss(yh: float, y: float) -> float:
    return -(y*math.log(yh)+(1-y)*math.log(1-yh))

def cost(yh: np.ndarray, y: np.ndarray):
    m, c = len(y), 0
    for i in range(m): 
        c += loss(yh[i], y[i])
    return c/m

def forward(x: np.ndarray, w: np.ndarray, b: float):
    return sigmoid(np.dot(w, x) + b)

def backward(x: np.ndarray, yh: np.ndarray, y: np.ndarray, w_dim: int):
    m = len(x)
    dz = yh - y
    dw = 1/m*np.dot(x, dz.T)
    db = 1/m*np.sum(dz)
    return dw, db

def train(iters: int, lr: float, x: np.ndarray, y: np.ndarray, w: np.ndarray, b: float):
    for i in range(iters):
        # forward
        yh = forward(x, w, b)
        c = cost(yh, y)
        print(f'c: {c:.4f}, yh: {yh}')

        # backward
        dw, db = backward(x, yh, y, len(w))
        
        # optimize
        w += -lr*dw
        b += -lr*db
    return c




In [4]:
w = np.zeros([X.shape[0]])
b = 0.0

loss = train(2, 0.01, X, Y, w, b)

c: 0.6931, yh: [0.5 0.5 0.5 0.5]
c: 0.6931, yh: [0.5 0.5 0.5 0.5]


In [7]:
# broadcasting example
A = np.array([
    [56.0, 0.0, 4.4, 68.0],
    [1.2, 104.0, 52.0, 8.0],
    [1.8, 135.0, 99.0, 0.9]])

print(A)
cal = A.sum(axis=0) # axis 0 is vertical axis, 1 is horizontal axis
print(cal)

perc = 100*A/cal.reshape(1,4)
print(perc)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]
[ 59.  239.  155.4  76.9]
[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]
