In [1]:
import torch
torch.__version__

'2.0.0a0'

In [10]:
scalar = torch.tensor(7)
print(scalar)
print(scalar.ndim)
print(scalar.shape)
num = scalar.item()
print(num)

tensor(7)
0
torch.Size([])
7


In [9]:
vector = torch.tensor([7, 7])
print(vector)
print(vector.ndim)
print(vector.shape)

tensor([7, 7])
1
torch.Size([2])


In [16]:
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX.shape

torch.Size([2, 2])

* scalars and vectors are lowercase
* matricies are uppercase

In [17]:
rnd_tensor = torch.rand(size=(3, 3))
rnd_tensor, rnd_tensor.dtype

(tensor([[0.8537, 0.8871, 0.2133],
         [0.4375, 0.2666, 0.9511],
         [0.5398, 0.5677, 0.6266]]),
 torch.float32)

In [18]:
random_img = torch.rand(size=(28, 28, 255))
random_img.shape, random_img.ndim

(torch.Size([28, 28, 255]), 3)

In [19]:
zeros = torch.zeros(size=(4,8))
ones = torch.ones(size=(2, 4))

In [21]:
choose_nums_range = torch.arange(0, 10, 1) # start, stop, steps
choose_nums_range

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
ten_zeros = torch.zeros_like(input=choose_nums_range)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [31]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                              dtype=None,
                              device=None,
                              requires_grad=False)
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

* most important: shape, dtype, device
* ops: add, sub, element mul, div, matmul

In [38]:
# normal ops:
# *, -, +
# torch.multiply, torch.subtract, torch.add

# @ -> not recommended to use
# torch.matmul or torch.mm (same thing)
# matmul is also called dot product

# row x column

In [39]:
# transpose:
# torch.transpose(tensor, dim0, dim1) the dimensions to transpose (for > 2 dims)
# tensor.T where tensor is the 2d tensor to transpose

In [46]:
# single linear feed forward layer
torch.manual_seed(42)
linear = torch.nn.Linear(in_features=784,
                        out_features=115)
x = torch.ones(size=(1, 784))
output = linear(x)

print(f"In shape: {x.shape}\n")
print(f"Out: \n{output}\n\nOut shape: {output.shape}")

In shape: torch.Size([1, 784])

Out: 
tensor([[-1.0221e+00,  3.3333e-01, -4.4196e-01,  3.6954e-01, -6.6991e-01,
         -1.0869e-01,  1.0467e+00, -1.4423e-01,  8.1657e-01, -5.4482e-01,
          3.3786e-01,  4.7608e-01, -2.3781e-01, -9.1405e-01, -4.6560e-02,
         -6.1687e-01, -7.6711e-02,  2.8819e-01, -3.7048e-01, -1.5974e-01,
          5.0816e-01,  1.4323e-01, -5.6566e-01, -6.8167e-01, -5.7136e-01,
         -3.8327e-01,  7.1025e-01,  2.9030e-01,  8.0512e-01, -4.8810e-01,
          8.9675e-02,  1.0378e+00,  7.0183e-01, -2.7763e-01,  1.0900e+00,
         -5.1458e-01, -1.1403e+00,  8.1332e-02, -8.5107e-02,  4.0625e-01,
         -1.5067e-02, -1.9607e-01,  1.9738e-01, -2.1913e-01,  3.8502e-01,
          2.1711e-01, -3.6357e-02,  6.3149e-01,  4.4924e-01,  3.0260e-01,
          1.4686e-01,  9.0243e-01,  9.8660e-01, -4.6107e-01,  4.5416e-01,
         -9.3773e-01,  2.6414e-01,  9.5601e-01, -1.2356e+00,  9.6001e-01,
         -1.2131e+00,  1.9815e-01,  3.0609e-01,  6.0750e-01, -2.9057e-01,


* aggregating matricies means taking them from more values to less values

In [52]:
X = torch.arange(0, 100, 10)
print(X)
print(f"Minimum: {X.min()}")
print(f"Maximum: {X.max()}")
print(f"Mean: {X.type(torch.float32).mean()}") # mean only works with floats
print(f"Sum: {X.sum()}")

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [56]:
tensor = torch.arange(10., 100., 10.)
tensor_float16 = tensor.type(torch.float16)
# the lower the precision number (16, 32, 64) the faster the computation
# and the smaller the overall model, but accuracy is sacrificed with this

In [57]:
# reshaping
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [67]:
x_reshaped = x.reshape(1, 7) # reshape
print(x_reshaped, x_reshaped.shape)

z = x.view(1, 7) # same tensor, diff dim
print(z, z.shape)

x_stacked = torch.stack([x, x, x, x], dim=0) # stack tensor ontop of itself
x_stacked

# squeeze removes all single dimensions from a tensor
# unsqueeze adds a dimension value of 1 to a specific index
# permute rearanges the order of axes values

tensor([[1., 2., 3., 4., 5., 6., 7.]]) torch.Size([1, 7])
tensor([[1., 2., 3., 4., 5., 6., 7.]]) torch.Size([1, 7])


tensor([[1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.]])

In [76]:
# indexing 
# goes outer dim -> inner dim
x = torch.arange(1, 10).reshape(1, 3, 3)
print(f"0th dim and 0 index of first dim: {x[:, 0]}")
print(f"All vals of 0th and 1st dim, but only index 1 of second dim: {x[:, :, 1]}")
# x[0, 0, :] is same as x[0][0]

0th dim and 0 index of first dim: tensor([[1, 2, 3]])
All vals of 0th and 1st dim, but only index 1 of second dim: tensor([[2, 5, 8]])


In [77]:
# pytorch and numpy
# torch.from_numpy(ndarray) np array to torch tensor
# torch .Tensor.numpy() torch tensor to np array

* also using google colab because gpu
* float16 -> half, float32 -> float, float64 -> double